"use client";
import { useEffect,useRef,useState } from "react";
const fields=[
{code:"AIR",cn:"AI 原生科研",en:"AI-Native Research",desc:"重构从科学问题到假设、实验与发现的完整科研闭环。",long:"Reimagine the research loop—from questions and hypotheses to experiments, evidence, and discovery."},
{code:"ANS",cn:"智能体原生系统",en:"Agent-Native Systems",desc:"以自主智能体为系统原点，构建协作、学习与行动的新型基础设施。",long:"Build systems designed from the ground up around autonomous, collaborative agents."},
{code:"SEI",cn:"自进化智能",en:"Self-Evolving Intelligence",desc:"探索从经验中学习、自我重组并持续提升的新一代智能。",long:"Explore intelligence that reorganizes itself and improves continuously through experience."},
{code:"ASD",cn:"自主科学发现",en:"Autonomous Discovery",desc:"构建与人类科学家协作，共同拓展知识边界的智能体科学家。",long:"Create agentic scientists that collaborate with humans to expand the frontier of knowledge."}
];
export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null);const[zh,setZh]=useState(true),[menu,setMenu]=useState(false),[active,setActive]=useState(0);
 useEffect(()=>{const c=canvasRef.current,x=c?.getContext("2d");if(!c||!x)return;let f=0;const pts=Array.from({length:55},()=>({x:Math.random(),y:Math.random(),v:(Math.random()-.5)*.00016}));const size=()=>{c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio};const draw=()=>{x.clearRect(0,0,c.width,c.height);pts.forEach(p=>{p.y+=p.v;if(p.y<0||p.y>1)p.v*=-1;x.fillStyle="#7fa3ff88";x.fillRect(p.x*c.width,p.y*c.height,1.2*devicePixelRatio,1.2*devicePixelRatio)});f=requestAnimationFrame(draw)};size();addEventListener("resize",size);draw();return()=>{cancelAnimationFrame(f);removeEventListener("resize",size)}},[]);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("in")),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
 const t=(cn:string,en:string)=>zh?cn:en;
 return <main className="site-v2"><canvas ref={canvasRef} className="particle-field" aria-hidden="true"/>
 <header className="nav"><a className="brand" href="#top"><span className="brand-symbol"><i/><i/><i/></span><span>ANative Lab<small>智能体原生智能实验室</small></span></a><nav className={menu?"open":""}><a href="#research">{t("科研","Research")}</a><a href="#systems">{t("系统","Systems")}</a><a href="#vision">{t("关于","About")}</a><a href="#people">{t("团队","People")}</a><a href="#contact">{t("加入我们","Join us")}</a></nav><div className="nav-tools"><button className="lang" onClick={()=>setZh(v=>!v)}>{zh?"EN":"中文"}</button><button className="menu" onClick={()=>setMenu(v=>!v)} aria-label="Toggle menu"><i/><i/></button></div></header>
 <section className="hero hero-v2" id="top"><div className="hero-no">01 <span>/</span> 05</div><div className="hero-copy"><div className="eyebrow">ANATIVE LAB · AI / AGENT / SCIENCE</div><h1>{zh?<>引领<br/>智能体原生智能</>:<>Leading<br/>Agent-Native<br/>Intelligence</>}</h1><p className="hero-cn">{t("以 AI 原生科研，塑造持续自主进化的未来","AI-Native Minds, Agent-Native Intelligence.")}</p><a href="#research" className="hero-more">{t("探索科研","Explore research")}<i>↗</i></a></div><div className="hero-visual" aria-hidden="true"><div className="halo h1"/><div className="halo h2"/><div className="halo h3"/><div className="core"><span>AN</span></div><div className="data-line d1">AUTONOMY <b>01</b></div><div className="data-line d2">EVOLUTION <b>02</b></div></div><div className="hero-bottom"><span>ANATIVE LAB © 2026</span><span>{t("向下探索","SCROLL TO EXPLORE")} ↓</span></div></section>
 <section className="research-v2" id="research"><div className="title-row reveal"><div><span className="kicker">01 / RESEARCH</span><h2>{t("科研","Research")}</h2></div><p>{t("探索人工智能与智能体原生智能的前沿创新","Exploring the frontiers of AI-native and agent-native intelligence")}</p></div><div className="research-tabs" role="tablist">{fields.map((f,i)=><button key={f.code} className={active===i?"active":""} onClick={()=>setActive(i)}><b>{f.code}</b><span>{zh?f.cn:f.en}</span></button>)}</div><div className="research-stage reveal"><div className="research-copy"><small>0{active+1} / 04</small><h3>{zh?fields[active].cn:fields[active].en}</h3><h4>{zh?fields[active].en:fields[active].cn}</h4><p>{zh?fields[active].desc:fields[active].long}</p><a href="#contact">{t("了解更多","Learn more")} ↗</a></div><div className="research-art" aria-hidden="true"><div className={`art-shape shape-${active}`}><i/><i/><i/><i/><strong>{fields[active].code}</strong></div><div className="art-meta"><span>ANATIVE / {fields[active].code}</span><span>EVOLVING INTELLIGENCE</span></div></div></div></section>
 <section className="systems-v2" id="systems"><div className="title-row dark reveal"><div><span className="kicker">02 / SYSTEMS</span><h2>{t("系统","Systems")}</h2></div><p>{t("打造支持自主学习、协作与持续进化的智能系统体系","Building the systems layer for autonomous learning, collaboration, and evolution")}</p></div><div className="system-map reveal"><div className="system-center"><small>ANATIVE CORE</small><strong>Agent-Native<br/>Intelligence</strong><span>自主 · 协作 · 进化</span></div><div className="system-ring r1"/><div className="system-ring r2"/><div className="system-node n1"><b>01</b> PERCEPTION</div><div className="system-node n2"><b>02</b> REASONING</div><div className="system-node n3"><b>03</b> ACTION</div><div className="system-node n4"><b>04</b> EVOLUTION</div></div><div className="system-stack">{["AI-Native Research Layer","Agent Collaboration Layer","Self-Evolution Engine","Autonomous Discovery Loop"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>{["QUESTIONS · HYPOTHESES · EVIDENCE","MEMORY · TOOLS · COORDINATION","REFLECTION · ADAPTATION · GROWTH","EXPERIMENT · VALIDATION · DISCOVERY"][i]}</small></div>)}</div></section>
 <section className="vision-v2" id="vision"><div className="vision-index">03</div><div className="vision-main reveal"><span className="kicker">VISION & MISSION</span><h2>{t("让智能持续进化，\n让科学加速发生。","Intelligence evolves.\nScience accelerates.")}</h2><p>{t("以 AI 原生科研，塑造智能体原生智能持续自主进化的未来，赋能人类创新，加速科学发现。","To shape a future through AI-native research, where agent-native intelligence evolves autonomously and continuously, empowers human innovation, and accelerates scientific discovery.")}</p></div><div className="vision-side reveal"><span>MISSION</span><p>{t("ANative Lab 致力于推动 AI 原生科研范式、智能体原生系统、自进化智能与自主科学发现，构建能够自主学习、协作与持续进化的新一代智能系统。","ANative Lab advances AI-native research paradigms, agent-native systems, self-evolving intelligence, and autonomous scientific discovery.")}</p><div><b>AI-NATIVE</b><b>AGENT-NATIVE</b><b>HUMAN-CENTERED</b></div></div></section>
 <section className="people-v2" id="people"><div className="title-row reveal"><div><span className="kicker">04 / PEOPLE</span><h2>{t("团队","People")}</h2></div><p>{t("以智能体拓展人类认知边界","Expanding the frontiers of human understanding through intelligent agents")}</p></div><article className="pi-v2 reveal"><div className="pi-code"><span>PRINCIPAL<br/>INVESTIGATOR</span><strong>M<br/>ZQ</strong><i/></div><div className="pi-text"><small>FOUNDER / LAB DIRECTOR</small><h3>{t("孟在桥","Zaiqiao Meng")}</h3><p>{t("ANative Lab 创始人、实验室负责人。探索 AI 原生科研与智能体原生智能，以新一代自主智能系统推动人类创新与科学发现。","Founder and principal investigator of ANative Lab. Exploring AI-native research and agent-native intelligence to advance human innovation and scientific discovery.")}</p><a href="https://mengzaiqiao.howone.app" target="_blank" rel="noreferrer">{t("个人主页","Profile")} ↗</a></div></article></section>
 <section className="join-v2" id="contact"><div className="join-wave"><i/><i/><i/></div><div className="join-inner reveal"><span className="kicker">05 / JOIN ANATIVE</span><h2>{t("共闯科研无人之境","Explore the unknown with us")}</h2><p>{t("我们寻找对智能、自主与科学发现抱有真正好奇心的同行者。","We are looking for curious minds ready to reinvent intelligence, research, and discovery.")}</p><a href="mailto:hello@anative.lab">{t("加入 ANative Lab","Join ANative Lab")} <b>↗</b></a></div></section>
 <footer className="footer-v2"><a className="brand" href="#top"><span className="brand-symbol"><i/><i/><i/></span><span>ANative Lab<small>AI-Native and Agent-Native Intelligence Laboratory</small></span></a><p>AI-Native Minds,<br/>Agent-Native Intelligence.</p><nav><a href="#research">Research</a><a href="#systems">Systems</a><a href="#people">People</a></nav><small>© 2026 ANATIVE LAB<br/>ALL RIGHTS RESERVED</small></footer>
 </main>
}
