"use client";
import { useEffect, useRef, useState } from "react";
const focus=[
{n:"01",code:"AIR",title:"AI-Native Research",cn:"AI 原生科研范式",text:"Reimagine the entire research loop — from questions and hypotheses to experiments, evidence, and discovery.",zh:"重构从问题、假设到实验、证据与发现的完整科研闭环。"},
{n:"02",code:"ANS",title:"Agent-Native Systems",cn:"智能体原生系统",text:"Build systems designed around autonomous agents, rather than adding agents as an afterthought.",zh:"以自主智能体为系统原点，而非将智能体作为后来附加的功能。"},
{n:"03",code:"SEI",title:"Self-Evolving Intelligence",cn:"自进化智能",text:"Explore intelligence that learns from experience, reorganizes itself, and improves continuously.",zh:"探索能够从经验中学习、自我重组并持续提升的智能。"},
{n:"04",code:"ASD",title:"Autonomous Discovery",cn:"自主科学发现",text:"Create agentic scientists that collaborate with humans to expand the frontier of knowledge.",zh:"构建与人类协作、共同拓展知识边界的智能体科学家。"}];
export default function Home(){
const canvasRef=useRef<HTMLCanvasElement>(null),[zh,setZh]=useState(false),[menu,setMenu]=useState(false);
useEffect(()=>{const canvas=canvasRef.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;let frame=0;const dots=Array.from({length:74},()=>({x:Math.random(),y:Math.random(),vx:(Math.random()-.5)*.0002,vy:(Math.random()-.5)*.0002}));const resize=()=>{canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio};const draw=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);dots.forEach((d,i)=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0||d.x>1)d.vx*=-1;if(d.y<0||d.y>1)d.vy*=-1;const x=d.x*canvas.width,y=d.y*canvas.height;ctx.fillStyle="rgba(98,255,202,.48)";ctx.beginPath();ctx.arc(x,y,1.2*devicePixelRatio,0,Math.PI*2);ctx.fill();dots.slice(i+1).forEach(o=>{const ox=o.x*canvas.width,oy=o.y*canvas.height,dist=Math.hypot(x-ox,y-oy),lim=145*devicePixelRatio;if(dist<lim){ctx.strokeStyle=`rgba(98,255,202,${.1*(1-dist/lim)})`;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ox,oy);ctx.stroke()}})});frame=requestAnimationFrame(draw)};resize();addEventListener("resize",resize);draw();return()=>{cancelAnimationFrame(frame);removeEventListener("resize",resize)}},[]);
useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("in")),{threshold:.14});document.querySelectorAll(".reveal").forEach(e=>obs.observe(e));return()=>obs.disconnect()},[]);
return <main><canvas ref={canvasRef} className="particle-field" aria-hidden="true"/><header className="nav"><a className="brand" href="#top"><span className="brand-mark">A<span>N</span></span><span>ANative Lab<small>AI-Native Intelligence</small></span></a><nav className={menu?"open":""}><a onClick={()=>setMenu(false)} href="#research">{zh?"研究":"Research"}</a><a onClick={()=>setMenu(false)} href="#vision">{zh?"愿景":"Vision"}</a><a onClick={()=>setMenu(false)} href="#people">{zh?"成员":"People"}</a><a onClick={()=>setMenu(false)} href="#contact">{zh?"加入我们":"Join us"}</a></nav><div className="nav-tools"><button className="lang" onClick={()=>setZh(v=>!v)}>{zh?"EN":"中"}</button><button className="menu" onClick={()=>setMenu(v=>!v)} aria-label="Toggle menu"><i/><i/></button></div></header>
<section className="hero" id="top"><div className="eyebrow"><span/> AI-NATIVE · AGENT-NATIVE · SELF-EVOLVING</div><h1>Intelligence,<br/><em>born native.</em></h1><p className="hero-cn">{zh?<>以 AI 原生科研<br/>塑造持续自主进化的未来</>:<>以 AI 原生之思<br/>探索智能体原生智能</>}</p><div className="hero-actions"><a href="#research" className="primary">{zh?"探索研究方向":"Explore our research"} <b>↗</b></a><a href="#vision" className="text-link">{zh?"了解我们的愿景":"Discover our vision"} ↓</a></div><div className="orbit" aria-hidden="true"><div className="orb-core">A<sup>N</sup></div><i/><i/><i/></div><div className="scroll-cue"><span>SCROLL TO EVOLVE</span><b/></div></section>
<section className="manifesto reveal" id="vision"><div className="section-label"><b>01</b> / VISION</div><p>{zh?"我们正在创造这样的未来":"We are building a future where"}</p><h2>{zh?<>智能不只回应 —<br/><span>它学习、协作，并持续进化。</span></>:<>intelligence does not merely respond —<br/><span>it learns, collaborates, and evolves.</span></>}</h2><div className="vision-copy">{zh?"以 AI 原生科研，塑造智能体原生智能持续自主进化的未来，赋能人类创新，加速科学发现。":"To shape a future through AI-native research, where agent-native intelligence evolves autonomously and continuously, empowers human innovation, and accelerates scientific discovery."}</div></section>
<section className="research" id="research"><div className="section-head reveal"><div className="section-label"><b>02</b> / RESEARCH</div><h2>{zh?"研究前沿":"Frontiers of"}<br/><em>{zh?"原生智能":"native intelligence"}</em></h2><p>{zh?"四条相互连接的研究路径，共同指向能自主学习、协作与进化的新一代智能系统。":"Four connected paths toward a new generation of intelligent systems capable of autonomous learning, collaboration, and evolution."}</p></div><div className="focus-grid">{focus.map(f=><article className="focus reveal" key={f.code}><div className="focus-top"><span>{f.n}</span><b>{f.code}</b></div><div className="node"><i/><i/><i/></div><h3>{zh?f.cn:f.title}</h3><small>{zh?f.title:f.cn}</small><p>{zh?f.zh:f.text}</p><a href="#contact">↗</a></article>)}</div></section>
<section className="mission"><div className="mission-orb"><i/><i/><i/><strong>∞</strong></div><div className="mission-copy reveal"><div className="section-label"><b>03</b> / MISSION</div><h2>{zh?<>重新定义<br/><em>科学如何发生。</em></>:<>Reinventing how<br/><em>science happens.</em></>}</h2><p>{zh?"ANative Lab 致力于推动 AI 原生科研范式、智能体原生系统、自进化智能与自主科学发现，构建能够自主学习、协作与持续进化的新一代智能系统，以智能体拓展人类认知边界，重塑科研与创新。":"ANative Lab advances AI-native research paradigms, agent-native systems, self-evolving intelligence, and autonomous scientific discovery. We build intelligent systems that expand the frontiers of human understanding and reinvent research and innovation."}</p><div className="principles"><span>01 <b>AUTONOMY</b></span><span>02 <b>COLLABORATION</b></span><span>03 <b>EVOLUTION</b></span></div></div></section>
<section className="people" id="people"><div className="section-head reveal"><div className="section-label"><b>04</b> / PEOPLE</div><h2>{zh?"由好奇心驱动。":"Driven by curiosity."}<br/><em>{zh?"为发现而生。":"Built for discovery."}</em></h2></div><article className="pi-card reveal"><div className="pi-visual"><span>MZQ</span><div className="scan"/></div><div className="pi-info"><small>FOUNDER · PRINCIPAL INVESTIGATOR</small><h3>{zh?"孟在桥":"Zaiqiao Meng"}</h3><p>{zh?"ANative Lab 创始人、实验室负责人。致力于探索 AI 原生科研与智能体原生智能，推动自主智能系统拓展人类创新的边界。":"Founder and principal investigator of ANative Lab, exploring AI-native research and agent-native intelligence to expand the boundaries of human innovation."}</p><a href="https://mengzaiqiao.howone.app" target="_blank" rel="noreferrer">{zh?"访问个人主页":"View profile"} ↗</a></div></article></section>
<section className="join" id="contact"><div className="join-grid"/><div className="join-copy reveal"><div className="section-label"><b>05</b> / JOIN ANATIVE</div><p>THE NEXT INTELLIGENCE<br/>WON&apos;T BUILD ITSELF.</p><h2>{zh?<>一起探索<br/><em>无人之境。</em></>:<>Let&apos;s explore<br/><em>the unknown.</em></>}</h2><a href="mailto:hello@anative.lab" className="primary">{zh?"与我们联系":"Start a conversation"} <b>↗</b></a></div><div className="big-a">A<sup>N</sup></div></section>
<footer><a className="brand" href="#top"><span className="brand-mark">A<span>N</span></span><span>ANative Lab<small>AI-Native and Agent-Native Intelligence Laboratory</small></span></a><p>AI-Native Minds,<br/>Agent-Native Intelligence.</p><div><a href="#research">Research</a><a href="#vision">Vision</a><a href="#people">People</a></div><small>© 2026 ANative Lab<br/>Evolving continuously.</small></footer></main>}
